# Generated by Django 5.2.10 on 2026-03-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score_record',
            field=models.IntegerField(default=0),
        ),
    ]
